version: '3.8'
services:
  app:
    build:
      context: .
      target: runner
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
