import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Provider from "@/components/context/Provider";
import NavBar from "@/components/NavBar";
import { Toaster } from "@/components/ui/Toaster";
import React from "react";
import { useSelectedLayoutSegment } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Caffeina Politica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  // const loginSegments = useSelectedLayoutSegment("authModal");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <NavBar />
          {authModal}
          <div>{children}</div>
          {/* {loginSegments} */}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
